# Generated by Django 3.2 on 2021-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('due_to_date', models.DateField(verbose_name='Дата сдачи')),
                ('owner', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('mark', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
