# Generated by Django 3.2 on 2021-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='owner',
            field=models.CharField(max_length=255, null=True, verbose_name='Владелец'),
        ),
    ]
